services:
  expo:
    build:
      context: ./docker/node
    container_name: react-native-expo
    ports:
      - "19000:19000"  # Metro bundler
      - "19001:19001"  # Fast refresh
      - "19002:19002"  # Expo dev tools
      - "8081:8081"    # React Native dev server
    volumes:
      - ./app:/app
      #- expo_node_modules:/app/node_modules
    working_dir: /app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    #command: ["npx", "expo", "start", "--tunnel"]
    command: ["tail", "-f", "/dev/null"]

#volumes:
#  expo_node_modules:
